name: Publish

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-local-vial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: python3 -m pip install --user qmk
      - run: qmk setup -y -H qmk_firmware
      - run: npm install
      - run: node index.js --local --vial
      #- run: node index.js --vial
      - uses: actions/upload-artifact@v3
        with:
          name: fw-local-vial
          path: |
            qmk_firmware/*.hex
            qmk_firmware/*.bin
            qmk_firmware/*.uf2

  build-s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: python3 -m pip install --user qmk
      - run: qmk setup -y -H qmk_firmware
      - run: npm install
      - run: node index.js --glob "splitkb*"
      - uses: actions/upload-artifact@v3
        with:
          name: fw-s
          path: |
            qmk_firmware/*.hex
            qmk_firmware/*.bin
            qmk_firmware/*.uf2

  publish:
    needs:
      - build-local-vial
      - build-s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: download
      - run: |
          while read v
          do
            find . -type f \( -iname "$v\_*\.hex" -o -iname "$v\_*\.bin" -o -iname "$v\_*\.uf2" \) | zip --junk-paths "$v" -@ &>/dev/null || true
          done
          zip --junk-paths firmwares *.zip
        working-directory: download
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          files: |
            download/firmwares.zip
